### ISSUE TITLE
cdnjs.cloudflare.com 404 error

### ISSUE THREAD

**Issue by MatthewHolmes** [Mantix/livewire-jodit-text-editor#1]
Thanks for this great package - it was just what I needed. I thought you might like to know that that cloudflare.com are no longer providing Jodit. Instead I used these with your package and it worked fine:
<link rel="stylesheet" href="https://unpkg.com/jodit@4.0.1/es2021/jodit.min.css" />
<script src="https://unpkg.com/jodit@4.0.1/es2021/jodit.min.js"></script>

**Comment by pieternaber** [comment]
Hi Matthew,
Thanks for informing me.
I've updated the readme file, so it uses unpkg.com instead of cloudflare.com.
